method:
  model_name: "ACOClassifierLSTM"
  model_param: "hp.lstm.input_size,hp.lstm.hidden_size,hp.lstm.num_layers"
  data_type: "aco"
  feature: "none" #"none,wavelet,mfcc"
---
lstm:
  input_size: 1
  hidden_size: 128
  num_layers: 2
---
data:
  #data_dir: '/root/svdd_torch/deepDS/data/aco_01'  #训练集位置
  data_dir: /mnt/g/DataBase/aco_seis_Dataset/aco_01
  test_size: 0.2
  channel: 0
  frame_length: 1024     #帧长度
---
train:
  epoch: 101
  batch_size: 64       #每次读取长度
  num_workers: 0       #并行
  checkpoint_interval: 2
  optimizer: 'adam'     #学习策略1
  sgd: 0.01
  adam: 0.001
  adabound:             #学习策略2
    initial: 0.001
    final: 0.05
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
  
  
  