method:
  model_name: "SeismicNet"
  model_param: ""
  data_type: "seis"
  feature: "none" #"none,wavelet,mfcc"
---
lstm:
  input_size: 1
  hidden_size: 128
  num_layers: 2
---
data:
  data_size: 100
  data_dir: '/root/svdd_torch/data/seis_01' #训练集位置
  test_size: 0.2
  frame_length: 1024     #帧长度
---
train:
  epoch: 270
  batch_size: 64       #每次读取长度
  num_workers: 0       #并行
  checkpoint_interval: 2
  optimizer: 'adam'     #学习策略1
  sgd: 0.01
  adam: 0.001
  adabound:             #学习策略2
    initial: 0.01
    final: 0.05
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
  
  
  
