method:
  model_name: "UrbanSoundModel"
  model_param: ""
  data_type: "aco"  #aco seis
  feature: "mfcc" #"none,wavelet,mfcc"
---
data:
  data_size: 100
  #data_dir: '/root/svdd_torch/deepDS/data/aco_01'  #训练集位置
  data_dir: data/aco_01
  test_size: 0.2
  channel: 0
  frame_length: 1024     #帧长度
---
train:
  epoch: 200
  batch_size: 64       #每次读取长度
  num_workers: 0       #并行
  checkpoint_interval: 2
  optimizer: 'adam'     #学习策略1
  sgd: 0.01
  adam: 0.001
  adabound:             #学习策略2
    initial: 0.001
    final: 0.05
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
  
  
  
